server:
    port: 2010

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josy870/EXAMEN-PARCIAL-DAD.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main

  security:
    user:
      name: root
      password: 123456